### ISSUE TITLE
Misleading title of window with error message when loading task files

### ISSUE THREAD

**Issue by B-Hartmann** [DCOR-dev/DCOR-Aid#82]
DCOR-Aid 0.16.1
Windows 10

I had problems uploading data (see #81) and as a solution deleted the jobs, deleted the draft datasets and removed the fields "dataset ID" and "id" from the .dcoraid task file. I then drag-and-dropped the task file again into DCOR-Aid and get a message that there is some issue because the task-ID is still the same and DCOR-Aid remembered processing the file, but cannot find any related dataset on the currently selected DCOR instance. So far, so good, see picture below.

The title of this window is a bit misleading though, cause there is no dataset ID in the task file, at least not when I _deleted it_ out of the file and then dragged it into DCOR-Aid again. I guess it will get one as soon as the task file is loaded in DCOR-Aid and then that new ID is used to search for the dataset online, but that is a bit confusing to users.

I would recommend keeping the title of that window with the message a bit more general: "There was an issue with the loaded task file."
And then be a bit more specific in the actual error message, for example, by writing "The task file you have loaded was processed before, but the datasets can not be found on the currently set DCOR instance. The dataset specified in the file: x.y.z
Possible reasons:
..."

![grafik](https://github.com/user-attachments/assets/b2af4701-78f4-453e-af3b-557d962e8144)

**Comment by paulmueller** [comment]
DCOR-Aid keeps track of the task IDs and dataset IDs. If you create an upload task and that task is given a task ID, then DCOR-Aid will always attribute that task ID to that dataset ID. Thus, technically speaking the error message is correct :smile: So, in order to avoid this error message, you must also remove the `task_id` of the upload job from the task file.

I have not anticipated advanced users modifying the task files. You are basically encountering a fail-safe mechanism that  yields a misleading error message in your case. I will update the error message to also cover this case.

**Comment by B-Hartmann** [comment]
Alright, thanks! (And sorry for all the unintended use and fiddling around with files that should not be changed by users like that :D)

**Comment by paulmueller** [comment]
That's fine. You didn't break anything. And thanks for reporting the issue.
